#!/bin/bash

set -e

if [ ! -n "$1" -o ! -n "$2" ]; then
        echo "Usage: ./`basename $0` <file with list of SRA IDs> <reference basename>"
        echo "Example: ./`basename $0` tests/01/sra_ids.txt tests/01/crassphage.fna"
        exit $E_BADARGS
fi

SRA_IDS=`basename $1`
REF_FILENAME=`basename $2`

export REF_BASENAME=`echo $REF_FILENAME | perl -p -e 's/\.[a-zA-Z]+$//'`
if [ "$REF_BASENAME" = "$REF_FILENAME" ]; then
    # ref file came in without extension - make a copy
    cp $REF_FILENAME $REF_FILENAME.fna
    REF_FILENAME="$REF_FILENAME.fna"
fi

echo "Creating a DAG for running $SRA_IDS against $REF_BASENAME ..."

TOP_DIR=`dirname $0`
TOP_DIR=`cd $TOP_DIR && pwd`

# used for directories, and track usage
export RUN_ID=`uuidgen`

# if not already defined, create a work dir for this run
if [ "x$WORK_DIR" = "x" ]; then
    WORK_DIR=$HOME/runs/$RUN_ID
    mkdir -p $WORK_DIR
    echo
    echo "Work directory is $WORK_DIR"

    # make copies of the input files
    cp $1 $WORK_DIR/
    cp $2 $WORK_DIR/$REF_BASENAME.fna
fi

# and of the templates/job files
cd $TOP_DIR
cp *.sh *.template $WORK_DIR/

cd $WORK_DIR

# index the ref genome
envsubst <index.template >index.submit
cat >>sra.dag <<EOF
JOB  INDEX  index.submit
EOF

# define final job before search jobs, so we can reference it in the
# parent-child relationships for the actual jobs
envsubst <local-prepare-outputs.template >local-prepare-outputs.submit
cat >>sra.dag <<EOF
JOB  PREPARE_OUTPUTS  local-prepare-outputs.submit
EOF

# build the HTCondor submit files and DAG
I=0
SUB_DIR=0
for SRA_ID in `cat $SRA_IDS | sort | uniq`; do

    if [ $(($I % 300)) -eq 0 ]; then
        export SUB_DIR=$(($SUB_DIR + 1))
        mkdir -p $SUB_DIR
    fi
    I=$(($I + 1))

    # for the job template
    export SRA_ID
    export OUTPUT_FILES="$SRA_ID.bam, $SRA_ID.bam.bai"

    # generate the job from the template    
    envsubst <search.template >$SUB_DIR/$SRA_ID.submit

    # add job to the dag
    cat >>sra.dag <<EOF

JOB  ID$SRA_ID  $SRA_ID.submit  DIR $SUB_DIR
RETRY ID$SRA_ID 3
PARENT INDEX CHILD ID$SRA_ID
PARENT ID$SRA_ID CHILD PREPARE_OUTPUTS
EOF

done



condor_submit_dag -notification NEVER -maxidle 1000 sra.dag


